
[env]
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 17

[font.normal]
family = "Hack"

[font.bold]
family = "Hack"

[font.italic]
family = "Hack"

[window]
opacity = 0.8

[window.dimensions]
columns = 100
lines = 40

[general]
import = [
  "~/.config/alacritty/themes/monokai_charcoal.toml"
]

